module.exports.getUsuarioValido = "SELECT A.SSUSRID,A.SSUSRDSC,A.SSUSRPSW,ifnull(A.SSUSRKEY,-1) SSUSRKEY,ifnull(B.CNCDIRID,-1) CNCDIRID, ifnull(B.CNUSERACC,'si') CNUSERACC ,ifnull(B.CNUSERESTATUS,'1') CNUSERESTATUS , ifnull(B.CNUSERCATCOL,'no') CNUSERCATCOL,B.CNUSERFOTO,"+
" ifnull(C.SMSUSERNOM,-1) SMSUSERNOM, ifnull(C.SMSUSERKEY,-1) SMSUSERKEY FROM siogen01.SSUSRI A"+
 " INNER JOIN siogen01.CNUSER B ON B.CNUSERID = A.SSUSRID "+
"  LEFT JOIN siogen01.SMSUSER C ON B.SMSUSERID = C.SMSUSERID" +
" WHERE A.SSUSRID = ?";

module.exports.getAreas = "SELECT A.RPFARESID RPFARESID,B.RPFARTRID RPFARTRID, B.RPFLINEA RPFLINEA, A.RPFARESIDC RPFARESIDC, A.RPFARESTITULO RPFARESTITULO, " +
"		   C.RPFARTRIDC RPFARTRIDC,C.RPFARTRDSC RPFARTRDSC, D.RPFREUNUSRID RPFREUNUSRID, B.RPFARES1EST RPFARES1EST, " +
"           B.PRTID portal, B.PRTPAGID pagina" +
"	FROM siogen01.RPFARES A   " +
"	    LEFT JOIN RPFARES1 B ON A.RPFARESID = B.RPFARESID " +
"		INNER JOIN RPFARTR C ON B.RPFARTRID = C.RPFARTRID  " +
"		INNER JOIN RPFREUN D ON A.RPFARESID = D.RPFREUNARESID AND B.RPFLINEA = D.RPFLINEA  " +
"		WHERE RPFREUNUSRID = ? "


module.exports.getModulosAreas = "SELECT RPFARESID, RPFLINEA, B.* FROM siogen01.RPFESTAREAMOD A " +
				   "     INNER JOIN siogen01.CNESMN B ON A.CNESMNID = B.CNESMNID " +
				   "	 WHERE  " +
				   "     RPFARESID = ? " +
				   "     AND  RPFLINEA = ? " +
                   " ORDER BY B.CNESMNDSC";
                   
module.exports.tieneConfiguracion = "SELECT CNESMNID " +     
                   " FROM siogen01.RPFESTAREAOTRM" + 
                   " WHERE 1 = 1" +					
                   " AND RPFESTAREAOTRM.CNESMNID =? AND RPFESTAREAOTRM.RPFLINEA = ? ";       
                   
module.exports.getMenuArbolConf =  "SELECT DISTINCT COALESCE(M.CNESMNID,'')CNESMNID, " +     
				   	"	COALESCE(N.CNMDLSID,'')CNMDLSID,   	" +	
				   	"	COALESCE(N.CNOTRMID,'')CNOTRMID,   	" +
					"	COALESCE(N.CNOTRMVER,'')CNOTRMVER, 	" +
					"	COALESCE(CNESMNOBJ,'')CNESMNOBJ,  	" +
					" 	COALESCE(CNESDSOP,'')CNESDSOP,  	" +
					"	COALESCE(CNESMNTCDO,'')CNESMNTCDO,	" +
					"	COALESCE(CNESMNTE,'')CNESMNTE,  	" +
					"	COALESCE(CNESMNRUTA,'')CNESMNRUTA,	" + 
					"	COALESCE(CNESMNRUDS,'')CNESMNRUDS,  " +
					"	COALESCE(CNESMNOBJ,'')CNESMNOBJ,	" +  
					"	COALESCE(CNESMNORI,'')CNESMNORI,  	" +
					"	COALESCE(CNESMN01,'')CNESMN01,		" + 
					"	COALESCE(CNESMN02,'')CNESMN02,   	" +
					"	COALESCE(CNESMN03,'')CNESMN03,  	" +
					"	COALESCE(CNESMN04,'')CNESMN04,  	" +
					"	COALESCE(CNESMN05,'')CNESMN05,  	" +
					"	COALESCE(CNESMN06,'')CNESMN06,  	" +
					"	COALESCE(CNESMN07,'')CNESMN07,  	" +
					"	COALESCE(CNESMN08,'')CNESMN08,		" + 
					"	COALESCE(CNESMN09,'')CNESMN09,  	" +
					"	COALESCE(CNESMN10,'')CNESMN10,      " +
					"	COALESCE(CNESMNHTML5,'')CNESMNHTML5," +
					"	COALESCE(CNESMNFLEX,'')CNESMNFLEX,   " +
					"	COALESCE(CNESMNTEMA,'')CNESMNTEMA,   " +
					"	COALESCE(CNESMNPRT,'')CNESMNPRT,   " +
					"	COALESCE(CNESMNPRTPAG,'')CNESMNPRTPAG,   " +
					"	COALESCE(CNESMN1IMP,'')CNESMN1IMP,   " +
					"	COALESCE(CNESMN1MOVIL,'')CNESMN1MOVIL,   " +
					"	COALESCE(CNESMN1TABLET,'')CNESMN1TABLET,   " +
					"	COALESCE(CNESMN1BGCOLO,'')CNESMN1BGCOLO,   " +
					"	COALESCE(CNESMN1TEXTCOLOR,'')CNESMN1TEXTCOLOR,   " +
					"	COALESCE(CNESMN1ICONO,'')CNESMN1ICONO   " +
		" FROM RPFESTAREAOTRM,CNESMN M INNER JOIN CNESMN1 N ON M.CNESMNID = N.CNESMNID" + 
		" WHERE 1 = 1" + 						
		" AND M.CNESMNID =? AND RPFESTAREAOTRM.RPFLINEA = ? AND " +
		"((RPFESTAREAOTRM.CNESMNID = N.CNESMNID AND RPFESTAREAOTRM.CNOTRMID = N.CNOTRMID) OR (N.CNOTRMID = ''))" +
        " ORDER BY CNESMN01, CNESMN02, CNESMN03, CNESMN04, CNESMN05, CNESMN06, CNESMN07, CNESMN08, CNESMN09, CNESMN10 "; 
        
module.exports.tieneConfiguracion = "SELECT CNESMNID " +     
                   " FROM siogen01.RPFESTAREAOTRM" + 
                   " WHERE 1 = 1" +					
                   " AND RPFESTAREAOTRM.CNESMNID =? AND RPFESTAREAOTRM.RPFLINEA = ? ";       
                   
module.exports.getMenuArbolConf =  "SELECT DISTINCT COALESCE(M.CNESMNID,'')CNESMNID, " +     
				   	"	COALESCE(N.CNMDLSID,'')CNMDLSID,   	" +	
				   	"	COALESCE(N.CNOTRMID,'')CNOTRMID,   	" +
					"	COALESCE(N.CNOTRMVER,'')CNOTRMVER, 	" +
					"	COALESCE(CNESMNOBJ,'')CNESMNOBJ,  	" +
					" 	COALESCE(CNESDSOP,'')CNESDSOP,  	" +
					"	COALESCE(CNESMNTCDO,'')CNESMNTCDO,	" +
					"	COALESCE(CNESMNTE,'')CNESMNTE,  	" +
					"	COALESCE(CNESMNRUTA,'')CNESMNRUTA,	" + 
					"	COALESCE(CNESMNRUDS,'')CNESMNRUDS,  " +
					"	COALESCE(CNESMNOBJ,'')CNESMNOBJ,	" +  
					"	COALESCE(CNESMNORI,'')CNESMNORI,  	" +
					"	COALESCE(CNESMN01,'')CNESMN01,		" + 
					"	COALESCE(CNESMN02,'')CNESMN02,   	" +
					"	COALESCE(CNESMN03,'')CNESMN03,  	" +
					"	COALESCE(CNESMN04,'')CNESMN04,  	" +
					"	COALESCE(CNESMN05,'')CNESMN05,  	" +
					"	COALESCE(CNESMN06,'')CNESMN06,  	" +
					"	COALESCE(CNESMN07,'')CNESMN07,  	" +
					"	COALESCE(CNESMN08,'')CNESMN08,		" + 
					"	COALESCE(CNESMN09,'')CNESMN09,  	" +
					"	COALESCE(CNESMN10,'')CNESMN10,      " +
					"	COALESCE(CNESMNHTML5,'')CNESMNHTML5," +
					"	COALESCE(CNESMNFLEX,'')CNESMNFLEX,   " +
					"	COALESCE(CNESMNTEMA,'')CNESMNTEMA,   " +
					"	COALESCE(CNESMNPRT,'')CNESMNPRT,   " +
					"	COALESCE(CNESMNPRTPAG,'')CNESMNPRTPAG,   " +
					"	COALESCE(CNESMN1IMP,'')CNESMN1IMP,   " +
					"	COALESCE(CNESMN1MOVIL,'')CNESMN1MOVIL,   " +
					"	COALESCE(CNESMN1TABLET,'')CNESMN1TABLET,   " +
					"	COALESCE(CNESMN1BGCOLO,'')CNESMN1BGCOLO,   " +
					"	COALESCE(CNESMN1TEXTCOLOR,'')CNESMN1TEXTCOLOR,   " +
					"	COALESCE(CNESMN1ICONO,'')CNESMN1ICONO   " +
		" FROM siogen01.RPFESTAREAOTRM,siogen01.CNESMN M INNER JOIN siogen01.CNESMN1 N ON M.CNESMNID = N.CNESMNID" + 
		" WHERE 1 = 1" + 						
		" AND M.CNESMNID =? AND RPFESTAREAOTRM.RPFLINEA = ? AND " +
		"((RPFESTAREAOTRM.CNESMNID = N.CNESMNID AND RPFESTAREAOTRM.CNOTRMID = N.CNOTRMID) OR (N.CNOTRMID = ''))" +
        " ORDER BY CNESMN01, CNESMN02, CNESMN03, CNESMN04, CNESMN05, CNESMN06, CNESMN07, CNESMN08, CNESMN09, CNESMN10 "; 

module.exports.getMenuArbol = "SELECT DISTINCT COALESCE(M.CNESMNID,'')CNESMNID, " +     
        "	COALESCE(N.CNMDLSID,'')CNMDLSID,   	" +	
        "	COALESCE(N.CNOTRMID,'')CNOTRMID,   	" +
        "	COALESCE(CNOTRMVER,'')CNOTRMVER, 	" +
        "	COALESCE(CNESMNOBJ,'')CNESMNOBJ,  	" +
        " 	COALESCE(CNESDSOP,'')CNESDSOP,  	" +
        "	COALESCE(CNESMNTCDO,'')CNESMNTCDO,	" +
        "	COALESCE(CNESMNTE,'')CNESMNTE,  	" +
        "	COALESCE(CNESMNRUTA,'')CNESMNRUTA,	" + 
        "	COALESCE(CNESMNRUDS,'')CNESMNRUDS,  " +
        "	COALESCE(CNESMNOBJ,'')CNESMNOBJ,	" +  
        "	COALESCE(CNESMNORI,'')CNESMNORI,  	" +
        "	COALESCE(CNESMN01,'')CNESMN01,		" + 
        "	COALESCE(CNESMN02,'')CNESMN02,   	" +
        "	COALESCE(CNESMN03,'')CNESMN03,  	" +
        "	COALESCE(CNESMN04,'')CNESMN04,  	" +
        "	COALESCE(CNESMN05,'')CNESMN05,  	" +
        "	COALESCE(CNESMN06,'')CNESMN06,  	" +
        "	COALESCE(CNESMN07,'')CNESMN07,  	" +
        "	COALESCE(CNESMN08,'')CNESMN08,		" + 
        "	COALESCE(CNESMN09,'')CNESMN09,  	" +
        "	COALESCE(CNESMN10,'')CNESMN10,      " +
        "	COALESCE(CNESMNHTML5,'')CNESMNHTML5," +
        "	COALESCE(CNESMNFLEX,'')CNESMNFLEX,   " +
        "	COALESCE(CNESMNTEMA,'')CNESMNTEMA,   " +
        "	COALESCE(CNESMNPRT,'')CNESMNPRT,   " +
        "	COALESCE(CNESMNPRTPAG,'')CNESMNPRTPAG,  " +
        "	COALESCE(CNESMN1IMP,'')CNESMN1IMP,   " +
        "	COALESCE(CNESMN1MOVIL,'')CNESMN1MOVIL,   " +
        "	COALESCE(CNESMN1TABLET,'')CNESMN1TABLET,   " +
        "	COALESCE(CNESMN1BGCOLO,'')CNESMN1BGCOLO,   " +
        "	COALESCE(CNESMN1TEXTCOLOR,'')CNESMN1TEXTCOLOR,   " +
        "	COALESCE(CNESMN1ICONO,'')CNESMN1ICONO   " +
        " FROM siogen01.CNESMN M INNER JOIN siogen01.CNESMN1 N ON M.CNESMNID = N.CNESMNID" + 
        " WHERE 1 = 1" + 						
        " AND M.CNESMNID =? " +
        " ORDER BY CNESMN01, CNESMN02, CNESMN03, CNESMN04, CNESMN05, CNESMN06, CNESMN07, CNESMN08, CNESMN09, CNESMN10 "; 